project:
  type: website
  output-dir: _site

website:
  title: "SCoRE"
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    logo-href: http://buffalobadger.github.io
    left:
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "SCoRE"
        href: index.qmd
      - text: "ToTaL Engineering"
        href: http://buffalobadger.github.io/ToTaL_Engineering
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: http://buffalobadger.github.io/about.html
  search:
    location: navbar
    type: overlay
  page-footer:
    background: light
    right: 
      - text: Copyright 2024, Carl Lund 
  favicon: graphics/BuffaloBadger_16_16.png
  sidebar:
    style: floating
    search: false
    collapse-level: 1
    contents: 
      - text: "Welcome"
        href: index.qmd
      - section: "Getting Started"
        contents:
          - text: "Preparing for SCoRE"
          - text: "Using SCoRE"
      - section: "___"
      - section: "Introduction"
        contents: 
          - text: "Reaction Engineering"
      - section: "Reactions and Rates"
        contents:
          - text: "Reactions and Reactors"
      - section: "Ideal Reactor Models"
        contents:
          - text: "Reactor Design Equations"
      - section: "Non-Continuous Ideal Reactors"
        contents:
          - text: "BSTR Response"
      - section: "Continuous Ideal Reactors"
        contents:
          - text: "Steady-State CSTR Response"
      - section: "Ideal Reactor Systems"
        contents:
          - text: "Reactor Networks"
      - section: "Kinetics Data Analysis"
        contents:
          - text: "Kinetics Data Generation"
      - section: "Non-Ideal Reactors"
        contents:
          - text: "The Age Function"
      - section: "___"
      - text: "Beyond the Basics"
      - text: "Additional Practice"
      - section: "___"
      - section: "Computational Methods"
        href: comp_methods.qmd
        contents:
          - text: "SCoRE Code Structure"
            href: comp_code_structure.qmd
          - text: "Common Tasks"
          - text: "Solving ATEs"
          - text: "Solving IVODEs"
          - text: "Solving CVODEs"
          - text: "Parameter Estimation"
          - text: "Solving BVODEs"
            href: comp_bvodes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
