project:
  type: website
  output-dir: _site

website:
  title: "SCoRE"
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    logo-href: http://buffalobadger.github.io
    left:
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "SCoRE"
        href: index.qmd
      - text: "ToTaL Engineering"
        href: http://buffalobadger.github.io/ToTaL_Engineering
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: http://buffalobadger.github.io/about.html
  search:
    location: navbar
    type: overlay
  page-footer:
    background: light
    right: 
      - text: Copyright 2024, Carl Lund 
  favicon: graphics/BuffaloBadger_16_16.png
  sidebar:
    style: floating
    search: false
    collapse-level: 1
    contents: 
      - section: "Welcome"
        href: index.qmd
        contents: 
          - text: "About SCoRE"
            href: about.qmd
          - text: "Before Starting SCoRE"
            href: before_starting.qmd
      - section: "___"
      - section: "Reactions and Rates"
        href: part_1.qmd
        contents:
          - text: "Chemical Reactions"
            href: class_1.qmd
          - text: "Rates and Rate Expressions"
            href: class_2.qmd
          - text: "Reaction Mechanisms"
            href: class_3.qmd
          - text: "Rate Determining Steps"
            href: class_4.qmd
          - text: "Catalyst and Charge Conservation"
            href: class_5.qmd
          - text: "Most Abundant Intermediates"
            href: class_6.qmd
          - text: "Part 1 Self-Assessment"
            href: assessment_1.qmd
      - section: "Ideal Reactor Models"
        href: part_2.qmd
        contents:
          - text: "Reactor Design Equations"
            href: class_7.qmd
          - text: "Reactor Modeling"
            href: class_8.qmd
      - section: "Non-Continuous Ideal Reactors"
        href: part_3.qmd
        contents:
          - text: "BSTR Response"
            href: class_9.qmd
          - text: "BSTR Optimization"
            href: class_10.qmd
          - text: "SBSTR Response"
            href: class_11.qmd
          - text: "SBSTR Optimization"
            href: class_12.qmd
          - text: "Non-Continuous Reactor Design"
            href: class_13.qmd
          - text: "Part 3 Self-Assessment"
            href: assessment_3.qmd
      - section: "Continuous Ideal Reactors"
        href: part_4.qmd
        contents:
          - text: "Steady-State CSTR Response"
            href: class_14.qmd
          - text: "Steady-State CSTR Optimization"
            href: class_15.qmd
          - text: "CSTR Steady-State Multiplicity"
            href: class_16.qmd
          - text: "Transient CSTR Response"
            href: class_17.qmd
          - text: "Steady-State CSTR Stability"
            href: class_18.qmd
          - text: "Steady-State PFR Response"
            href: class_19.qmd
          - text: "Steady-State PFR Optimization"
            href: class_20.qmd
          - text: "Transient PFR Response"
            href: class_21.qmd
          - text: "Packed Bed PFR Response"
            href: class_22.qmd
          - text: "Continuous Reactor Design"
            href: class_23.qmd
          - text: "Part 4 Self-Assessment"
            href: assessment_4.qmd
      - section: "Ideal Reactor Systems"
        href: part_5.qmd
        contents:
          - text: "Reactor Networks"
            href: class_24.qmd
          - text: "Thermally Back-Mixed PFRs"
            href: class_25.qmd
          - text: "Recycle PFRs"
            href: class_26.qmd
          - text: "Part 5 Self-Assessment"
            href: assessment_5.qmd
      - section: "Kinetics Data Analysis"
        href: part_6.qmd
        contents:
          - text: "Kinetics Data Generation"
            href: class_27.qmd
          - text: "BSTR Kinetics Data Analysis"
            href: class_28.qmd
          - text: "CSTR Kinetics Data Analysis"
            href: class_29.qmd
          - text: "PFR Kinetics Data Analysis"
            href: class_30.qmd
          - text: "Differential Data Analysis"
            href: class_31.qmd
          - text: "Part 6 Self-Assessment"
            href: assessment_6.qmd
      - section: "Non-Ideal Reactors"
        href: part_7.qmd
        contents:
          - text: "Axial Dispersion Models"
            href: class_32.qmd
          - text: "The Age Function"
            href: class_33.qmd
          - text: "Segregated Flow Models"
            href: class_34.qmd
          - text: "Zoned Reactor Models"
            href: class_35.qmd
          - text: "Part 7 Self-Assessment"
            href: assessment_7.qmd
      - section: "___"
      - text: "Beyond the Basics"
        href: beyond.qmd
      - text: "Additional Practice"
        href: practice.qmd
      - section: "___"
      - section: "Computational Methods"
        href: computation.qmd
        contents:
          - text: "Common Tasks"
            href: comp_tasks.qmd
          - text: "Solving ATEs"
            href: comp_ates.qmd
          - text: "Solving IVODEs"
            href: comp_ivodes.qmd
          - text: "Solving DAEs"
            href: comp_daes.qmd
          - text: "Parameter Estimation"
            href: comp_param_est.qmd
          - text: "Solving BVODEs"
            href: comp_bvodes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
