project:
  type: website
  output-dir: _site

website:
  title: "SCoRE"
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    logo-href: http://buffalobadger.github.io
    left:
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "SCoRE"
        href: index.qmd
      - text: "ToTaL Engineering"
        href: http://buffalobadger.github.io/ToTaL_Engineering
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: http://buffalobadger.github.io/about.html
  search:
    location: navbar
    type: overlay
  page-footer:
    background: light
    right: 
      - text: Copyright 2024, Carl Lund 
  favicon: graphics/BuffaloBadger_16_16.png
  sidebar:
    style: floating
    search: false
    collapse-level: 1
    contents: 
      - text: "Welcome"
        href: index.qmd
      - section: "Getting Started"
        contents:
          - text: "Preparing for SCoRE"
            href: preparing.qmd
          - text: "Using SCoRE"
            href: using.qmd
      - section: "___"
      - section: "Introduction"
        contents: 
          - text: "Class 1: Reaction Engineering, Ethics, and Safety"
            href: class_1.qmd
          - text: "Class 2: Reactions and Reaction Progress"
            href: class_2.qmd
      - section: "Rate Expressions"
        contents:
          - text: "Class 3: Rates and Rate Expressions"
            href: class_3.qmd
          - text: "Class 4: Reaction Mechanisms"
            href: class_4.qmd
          - text: "Class 5: Rate-Determining Steps"
            href: class_5.qmd
          - text: "Class 6: Catalyst and Charge Conservation"
            href: class_6.qmd
          - text: "Class 7: Most Abundant Intermediate"
            href: class_7.qmd
      - section: "Reaction Engineering Analysis"
        contents:
          - text: "Class 8: Reaction Engineering Models"
            href: class_8.qmd
          - text: "Class 9: Reaction Engineering Tasks"
            href: class_9.qmd
          - text: "Class 10: Completing Reaction Engineering Tasks"
            href: class_10.qmd
      - section: "Non-Continuous Ideal Reactors"
        contents:
          - text: "Class 11: BSTR Response"
            href: class_11.qmd
          - text: "Class 12: BSTR Optimization"
            href: class_12.qmd
          - text: "Class 13: SBSTR Response"
            href: class_13.qmd
          - text: "Class 14: SBSTR Optimization"
            href: class_14.qmd
          - text: "Class 15: Design of Non-Continuous Reactors"
            href: class_15.qmd
      - section: "Continuous Ideal Reactors"
        contents:
          - text: "Class 16: Steady-State CSTR Response"
            href: class_16.qmd
          - text: "Class 17: Steady-State CSTR Optimization"
            href: class_17.qmd
          - text: "Class 18: CSTR Steady-State Multiplicity"
            href: class_18.qmd
          - text: "Class 19: Transient CSTR Response"
            href: class_19.qmd
          - text: "Class 20: CSTR Steady-State Stability and Sensitivity"
            href: class_20.qmd
          - text: "Class 21: Steady-State PFR Response"
            href: class_21.qmd
          - text: "Class 22: Steady-State PFR Optimization"
            href: class_22.qmd
          - text: "Class 23: Transient PFR Response"
            href: class_23.qmd
          - text: "Class 24: Packed Bed PFRs"
            href: class_24.qmd
          - text: "Class 25: Design of Continuous Reactors"
            href: class_25.qmd
      - section: "Ideal Reactor Systems"
        contents:
          - text: "Class 26: Reactor Networks"
            href: class_26.qmd
          - text: "Class 27: Thermally Back-Mixed PFRs"
            href: class_27.qmd
          - text: "Class 28: Recycle PFRs"
            href: class_28.qmd
      - section: "Kinetics Data Analysis"
        contents:
          - text: "Class 29: Generation and Analysis of Kinetics Data"
            href: class_29.qmd
          - text: "Class 30: Kinetics Data Analysis Using Linearized Models"
            href: class_30.qmd
          - text: "Class 31: Differential Kinetics Data Analysis"
            href: class_31.qmd
          - text: "Class 32: Analysis of Kinetics Data from a BSTR"
            href: class_32.qmd
          - text: "Class 33: Analysis of Kinetics Data from a CSTR"
            href: class_33.qmd
          - text: "Class 34: Analysis of Kinetics Data from a PFR"
            href: class_34.qmd
      - section: "Non-Ideal Reactors"
        contents:
          - text: "Class 35: Age Distribution Functions"
            href: class_35.qmd
          - text: "Class 36: A Segregated Flow Reactor Model"
            href: class_36.qmd
          - text: "Class 37: Steady-State Axial Dispersion Reactor Model"
            href: class_37.qmd
          - text: "Class 38: Zoned Reactor Models"
            href: class_38.qmd
      - section: "Beyond the Basics"
        contents:
          - text: "Class 39: Intermediate Reaction Engineering"
            href: class_39.qmd
      - text: "Additional Practice"
        href: practice.qmd
      - section: "___"
      - section: "Computational Supplements"
        contents:
          - text: "Equations and Solvers"
            href: eqns_and_solvers.qmd
          - text: "Computer Code"
            href: comp_code.qmd
          - text: "Solving ATEs"
            href: solving_ates.qmd
          - text: "Solving IVODEs"
            href: solving_ivodes.qmd
          - text: "Solving DAEs"
            href: solving_daes.qmd
          - text: "Solving BVODEs"
            href: solving_bvodes.qmd
          - text: "Estimating Parameters"
            href: parameter_est.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
