
{{< include includes/_top_logo.qmd >}}

# Class 28 - BSTR Kinetics Data Analysis {.ct}

## Preparation Assignment {.ch} 

[content forthcoming]

**Reaction Engineering Basics, Example 19.5.1**

[links to videos forthcoming]

Numerical implementations of the solution using Matlab, [reb_19_5_1.m](reb_examples/reb_19_5_1/reb_19_5_1.m), [reb_19_5_1_diff.m](reb_examples/reb_19_5_1/reb_19_5_1_diff.m), and Python, [reb_19_5_1.py](reb_examples/reb_19_5_1/reb_19_5_1.py) and [reb_19_5_1_diff.py](reb_examples/reb_19_5_1/reb_19_5_1_diff.py). [Data File](reb_examples/reb_19_5_1/reb_19_5_1_data.csv_)

**Reaction Engineering Basics, Example 19.5.2**

[links to videos forthcoming]

Numerical implementations of the solution using Matlab, [reb_19_5_2.m](reb_examples/reb_19_5_2/reb_19_5_2.m), [reb_19_5_2_linear.m](reb_examples/reb_19_5_2/reb_19_5_2_linear.m) and Python, [reb_19_5_2.py](reb_examples/reb_19_5_2/reb_19_5_2.py) and  [reb_19_5_2_linear.py](reb_examples/reb_19_5_2/reb_19_5_2linear.py). [Data File](reb_examples/reb_19_5_2/reb_19_5_2_data.csv_)

**Reaction Engineering Basics, Example 19.5.3**

[links to videos forthcoming]

Numerical implementations of the solution using Matlab, [reb_19_5_3.m](reb_examples/reb_19_5_3/reb_19_5_3.m), and Python, [reb_19_5_3.py](reb_examples/reb_19_5_3/reb_19_5_3.py). [Data File](reb_examples/reb_19_5_3/reb_19_5_3_data.csv_)

**Reaction Engineering Basics, Example 19.5.4**

[links to videos forthcoming]

Numerical implementations of the solution using Matlab, [reb_19_5_4.m](reb_examples/reb_19_5_4/reb_19_5_4.m), and Python, [reb_19_5_4.py](reb_examples/reb_19_5_4/reb_19_5_4.py). [Data File](reb_examples/reb_19_5_4/reb_19_5_4_data.csv_)

## Class 28 {.ch}

[content forthcoming]

## Practice Assignment {.ch}

[content forthcoming]

{{< include includes/_bottom_license.qmd >}}
