
{{< include includes/_top_logo.qmd >}}

# Welcome! {.ct} 

:::{.callout-important icon=true}
## [SC]{style="color:blue"}o[RE]{style="color:red"} is not yet complete

Content is being added to [SC]{style="color:blue"}o[RE]{style="color:red"} in parallel with the revision of the first draft of *Reaction Engineering Basics.* I hope to complete both by the end of 2025.

:::

## [SC]{style="color:blue"}o[RE]{style="color:red"} Site Status {.ch}



Eventually this sub-section will be replaced with a link to a welcome video. For now, however, I will be using it to log content as it is added to the site.

7/25
: Added Computational Supplements Section and placeholder pages for all classes

8/14/25
: Added Preparation Assignments for Classes 1, 2, and 3 and Practice Assignment for Class 1.

## [SC]{style="color:blue"}o[RE]{style="color:red"} Learning Outcomes {.ch}

Upon successful completion of this course, students will possess the component knowledge and skills necessary for reaction engineering analysis and be able to use them to

1. Postulate an empirical, mechanistic or theoretical rate expression for a given reaction.
2. Using kinetics data from an ideal reactor, estimate values for rate expression parameters, assess the accuracy of the rate expression, and evaluate its suitability.
3. Formulate steady-state and/or transient models of ideal batch, semi-batch, and continuous flow stirred tank reactors and plug flow reactors, use them to predict the response of, optimize, or design a reactor, and qualitatively rationalize or explain the results on a physical/chemical basis.
4. Formulate steady-state models of simple CSTR and/or PFR systems that may include multiple reactors, stream splits, stream mixing and heat exchangers, use them to predict the response of, optimize or design a system of that type, and qualitatively rationalize or explain the results on a physical/chemical basis.
5. Formulate steady-state zoned reactor models, segregated-flow reactor models (including, when necessary, numerical approximation of the age function using experimental stimulus/response data) and steady-state axial dispersion reactor models and use them to predict reactor response.

{{< include includes/_bottom_license.qmd >}}
